<Project>

  <PropertyGroup>

    <Version>0.7.3</Version>

    <Authors>mruether</Authors>
    <Copyright>mruether</Copyright>

    <Nullable>enable</Nullable>
    <LangVersion>8.0</LangVersion>

    <RepositoryUrl>https://github.com/mnemonic-bit/SampleNuget.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>

  </PropertyGroup>

</Project>