<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../Common/CommonSample.props"/>
  
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net6.0;net8.0</TargetFrameworks>
    <OutputType>library</OutputType>

    <AssemblyName>SampleNuget</AssemblyName>
    <RootNamespace>SampleNuget</RootNamespace>

    <Title>Nuget sample project</Title>
    <PackageReadmeFile>README.md</PackageReadmeFile>

    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>

    <PackageId>mnemonic-bit.SampleNuget</PackageId>
    <Description>Nuget sample project for demonstrating how to push a Nuget from Github.</Description>
    <PackageTags>sample, nuget, package</PackageTags>
	  <IsPackable>true</IsPackable>
    <IsTrimmable>true</IsTrimmable>
    
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <Import Project="../Common/SourceLink.props"/>
  
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
